"""Addd users to role

Revision ID: f94edc77b8c3
Revises: 3a6602ef0c44
Create Date: 2022-01-11 16:57:23.348569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f94edc77b8c3'
down_revision = '3a6602ef0c44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
